### ISSUE TITLE
Can't cross-reference textures from a Hydra instance to another

### ISSUE THREAD

**Issue by ritchse** [hydra-synth/hydra-synth#134]
Basically this doesn't work:

```js
const hydra1 = new Hydra({ makeGlobal: true });
osc().out()


const hydra2 = new Hydra({ makeGlobal: false });
const h2 = hydra2.synth;
h2.src(o0).out(h2.o0)
```

Expected to have the o0 from hydra1 to appear on h2.o0

I'm not sure why this wouldn't work, going through the source code I haven't found anything that might cause this. It seems it reference h2's o0 instead of hydra1's o0.

**Comment by ojack** [comment]
This isn't possible because each hydra instance is a separate webgl
context, with its own resources

**Comment by ojack** [comment]
https://www.khronos.org/webgl/wiki/SharedResouces

**Comment by ritchse** [comment]
Ah I see! Thanks for the answer, I really couldn't figure out why it wouldn't work. Will close because It's clearly not possible to achieve.
