### ISSUE TITLE
Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by chaoslogick** [hydra-synth/hydra-synth#145]
In my vue 3 project, I have installed `hydra-synth` with `yarn add`, written a standard import, and the page crashes due to js error. Below is the console error:

```
Uncaught ReferenceError: global is not defined
    js browser.js:1
    __require chunk-DFKQJ226.js:8
    js index.js:3
    __require chunk-DFKQJ226.js:8
    <anonymous> hydra-synth.js:3
```

**Comment by chaoslogick** [comment]
Issue in hydra-synth dependency, not in hydra-synth itself

**Comment by felixroos** [comment]
getting the same error using vite as a bundler. seems like the browserify adds it as part of its build step. how did you fix it?
