### ISSUE TITLE
Black screen in some browsers

### ISSUE THREAD

**Issue by polymorphicengine** [hydra-synth/hydra-synth#32]
When opening https://hydra-editor.glitch.me/ with microsoft edge there appears only a black screen. The error the console gives me is: 

SCRIPT438: SCRIPT438: Object doesn't support property or method 'captureStream' bundle.js (22526,7)

I know this issue exists also on some browsers on mobile phones, didn't check myself though.

**Comment by micuat** [comment]
it works on my windows' edge - unless more details are given (what version of the operating system / browser etc) should we close the issue? @ojack

**Comment by zachkrall** [comment]
@micuat this might have been fixed with #79 ?

**Comment by micuat** [comment]
it could be. and I don't think the issue is relevant anymore - if anyone finds this issue, please reopen or open a new issue
