### ISSUE TITLE
Multiple hydra instances in one page

### ISSUE THREAD

**Issue by ojack** [hydra-synth/hydra-synth#44]

**Comment by zachkrall** [comment]
is there a bundled version of hydra-synth somewhere?

**Comment by ojack** [comment]
no yet :)

**Comment by ojack** [comment]
@zachkrall https://unpkg.com/hydra-synth@1.1.1/dist/hydra-synth.js :)

**Comment by zachkrall** [comment]
@ojack yes! such a great idea 👍

**Comment by ojack** [comment]
But dont share widely quite yet! I am still working on documenting better how to use hydra synth + the most recent changes

**Comment by zachkrall** [comment]
lmk if you want help with anything in particular :)

**Comment by ojack** [comment]
Hey yes! If you want to try out the new version (of hydra-synth) and document any errors. Let me know when you get this and we can dm :)

**Comment by amounym** [comment]
Hi, don't know if that's the right place to ask but is there a way to have several hydra canvas on the same html page? I've been trying to figure it out but it seems like hydra only allow one instance to exist on the page.

**Comment by TheWispy** [comment]
A workaround to this is to use iframes linking to pages with hydra on them. Not sure if that's the right way to go about it, though.

**Comment by ojack** [comment]
Yes that is probably the easiest way! But it should also work with
hydra-synth. Could you upload a code example of what you have tried?

**Comment by amounym** [comment]
I've tried two ways, first was just with the hydra synth, inside the instance of hydra I changed
`      var hydra = new Hydra({
        canvas: document.getElementById("myCanvas")
      })` to `canvas: document.getElementsByClassName("myCanvas")` and then changed my canvas id to a class so I could have two canvas but I ran into an error I didn't understand.

The second way, I tried to copy the content of the Hydra canvas into a blank canvas with a javascript function but that was a longer route and it didn't work - you can find my code [here](https://glitch.com/edit/#!/hydra-multiple-canvases) if you want to have a look, I'd really appreciate your help!

Thank you :)

**Comment by ojack** [comment]
Here is an example: https://glitch.com/edit/#!/hydrax2?path=index.html:36:5

However, it seems like a lot isn't working right now with non-global mode,
especially related to blending and feedback.

**Comment by amounym** [comment]
Thank you Olivia for sending the code example!

Based on your code I've been able to do [this ](https://glitch.com/edit/#!/join/08ac503e-336b-4313-a376-9ecf8dc8ff92), multiple canvases work fine with simple hydra code but the examples from the website trigger the error `TypeError: Cannot read property 'getTexture' of undefined` is that what you mean when saying a lot isn't working?

**Comment by ojack** [comment]
yes :)

**Comment by amounym** [comment]
Okok, let me know if there's anything I can do to help resolve the issue :)

**Comment by charlieroberts** [comment]
Just want to ping this issue as I'm dealing with the same `getTexture` bug... for my use case (live coding multiple calls to the hydrasynth constructor) there doesn't seem to be any workarounds besides dynamically reloading the entire library between instantiating each synth. Which is odd... seems like some sort of global flag must be being set on the lib itself? and then when you load a fresh copy of the lib everything is back to normal...

**Comment by ojack** [comment]
hmmm yes thank you for the reminder. have been really buried with work lately and havent had a chance to work on this yet :/
@charlieroberts how are you using it exactly? Wondering because  I have also been working on a shader generator with no gl dependencies that just converts a hydra string to a shader, which may be useful to you as well.

**Comment by charlieroberts** [comment]
Just trying to cleanup the workflow for using Hydra as a texture in marching.js. Here's an example:

https://charlieroberts.github.io/marching/playground/index.htm?dXNlKCdoeWRyYScpLnRoZW4oICgpPT4gewogIGggPSBIeWRyYSgpCiAgb3NjKCA1MCwuMTUsLjI1ICkubW9kdWxhdGUoIG5vaXNlKDE1KSApLm91dCgpCiAgCiAgbWFyY2goCiAgICBtID0gQm94KCkudGV4dHVyZSggaC50ZXh0dXJlKCkgKQogICkKICAucmVuZGVyKCdtZWQnKQogIC5jYW1lcmEoMCwwLDQpCiAgCiAgb25mcmFtZSA9IHQgPT4gbS5yb3RhdGUodCo1LCAuNSwxLC41ICkKICAKICBoLnRleHR1cmUuc3RyZW5ndGggPSAuNQp9KQo=

Right now I store a reference when I create a `Hydrasynth` instance and then reuse that reference if the marching.js `Hydra` function is called again... this prevents the `getTexture` bug but isn't ideal, and would probably screw things up if I wanted multiple hydra textures for different 3D objects.

An independent shader generator would potentially be great for this use case!!! nice.

**Comment by ffd8** [comment]
Just ran into the issue while hoping to have 2+ parallel hydra instances (different textures on different objects). 
non-global mode is working quite well (adding prefix all over the place).. but I hit bug when trying to make two:
```
let hc = document.createElement('canvas')
hc.width = 1280
hc.height = 720

let hc2 = document.createElement('canvas')
hc2.width = 1280
hc2.height = 720

let synth = new Hydra({detectAudio: false, canvas: hc, makeGlobal: false}).synth // scoped instance
let synth2 = new Hydra({detectAudio: false, canvas: hc2, makeGlobal: false}).synth // scoped instance


synth.noise(8, .5).modulate(synth.noise(5), .3).modulate(synth.osc(5, .1, .2), .3).out()
// synth2.osc().out() // fails above.. 
```

If I disable `let synth2...`, the single instance works fine. 
When activating `let synth2...`, returns the following error (first line error repeats):
```
WebGL: INVALID_OPERATION: useProgram: program not valid
WebGL: INVALID_OPERATION: drawArrays: no valid shader program in use
```
Here's a [glitch.com](https://glitch.com/edit/#!/hydra-multi-instance-test?path=index.html%3A7%3A24) example to try and recreate.

**Comment by micuat** [comment]
@ojack this is fixed too :)

**Comment by avivash** [comment]
hi @ojack, thanks for making this library, it's great! I'm having an issue when I have multiple instances trying to use `.modulate`. Do you know if there's a way around this? It's throwing an error on `getTexture`. I'm on the latest version. thanks 🙏🏼

**Comment by micuat** [comment]
@avivash thanks for the report, indeed I had the same issue recently. I will look into it later.

**Comment by avivash** [comment]
thanks @micuat! I'll try to backtrace the issue myself too 👍🏼

**Comment by micuat** [comment]
It broke between 1.3.18 and 1.3.21

**Comment by avivash** [comment]
> It broke between 1.3.18 and 1.3.21
> 
> edit: 1.3.20 ([3c76dfa](https://github.com/hydra-synth/hydra-synth/commit/3c76dfafc9ef3036594133b2f9730529d9edda8e)) works too

Amazing! Thanks @micuat, I've got it working now with `1.3.18`. I really appreciate the quick reply 👍🏼

**Comment by micuat** [comment]
![image](https://user-images.githubusercontent.com/1835081/198364205-873870d8-e164-490a-a5e2-4aeeab26b439.png)

for some reason, combine/combineCoord have vec4, vec4, ... instead of just one vec4. And this is why it's causing the error

**Comment by micuat** [comment]
The fix from https://github.com/hydra-synth/hydra-synth/issues/95 did not work. I feel that there are a couple of things that are broken during the initialization of the second hydra, such as `transforms` overwritten by the second instance because it is somehow exposed globally. hmm

**Comment by avivash** [comment]
ahh interesting 👀. I should hopefully be wrapping this project up today/tomorrow then I'd be happy to poke around the code to help debug

**Comment by micuat** [comment]
so it was just exposed globally. fixed in 41a0aa11a56caf08a072e94c5216e4a43ae187aa (sorry I forgot to make PR and instead pushed to main, I hope it's ok @ojack )

**Comment by ojack** [comment]
Hmm make sure to add to the Changelog and update the version number in
package.json.... I still need to publish for the live version to be
updated. Thx for fixing!!

**Comment by micuat** [comment]
sorry I did edit package.json directly but I did it again with `npm version patch` to make sure - also edited changelog in https://github.com/hydra-synth/hydra-synth/commit/e302a9c712b29d956862fe380101726c8627e635
